#!/bin/bash

if [ -z "$1" ]; then
	echo
	echo "No function specified"
	echo
	echo "pfunc command syntax: pfunc <function>"
	echo		
	echo "Example: pfunc func_get_args"
	echo
	exit 1
else	
	func=$1
	url="http://php.net/$func"
	contents=$(lynx -dump $url)
	
	if [[ $contents == *"doesn't exist. Closest matches"* ]]; then
		echo
		echo >&2  "'$func' is not a valid PHP function"
		echo
		exit 1
	fi

	clear
	awk -v a="$contents" -v b="$func" 'BEGIN{gsub(/\"\n\"/, "\"\\n\"", a); print substr(a, index(a, b" —"), index(a, "See Also") - index(a, b" —"))}' 

fi
